name: Main Test and Build Dockers
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          lein: 2.9.1

      - name: Run lein test
        run: lein test

  build-back:
    name: Build Back
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t myexeym/hs-back -f ./kuber/back/Dockerfile .

#      - name: Upload image
#        uses: ishworkh/docker-image-artifact-upload@v1
#        with:
#          image: "myexeym/hs-back:latest"

  build-front:
    name: Build Front
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t myexeym/hs-front -f ./kuber/front/Dockerfile .

#      - name: Upload image
#        uses: ishworkh/docker-image-artifact-upload@v1
#        with:
#          image: "myexeym/hs-front:latest"